name: Build test

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Test de démarrage du conteneur Docker
        run: |
          docker run -d -p 3000:3000 --name api-test nodejs_postgres-node:latest
          sleep 10 
          
          # NOUVEAU : On affiche les logs du conteneur pour voir l'erreur Node.js            echo "=== LOGS DU CONTENEUR ==="
          docker logs api-test
          echo "========================="
          
          curl -f http://localhost:3000/ || exit 1