name: Build test

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker
        run: docker compose up -d --build nodejs_postgres-node:latest .

      - name: Attente du démarrage
        run: sleep 10

      - name: Lancement du curl
        run: |
            curl -X GET http://localhost:3000/api/